# Generated by Django 2.2.6 on 2021-04-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp_in', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.CharField(blank=True, max_length=140)),
                ('oxigenacion', models.CharField(blank=True, max_length=140)),
            ],
        ),
    ]
