# Generated by Django 2.2.6 on 2021-04-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='oxigenacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='temperatura',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
